name: Deploy pages
on: 
  push:
    paths:
      - 'presentations/**'
  workflow_dispatch:
jobs:
  deploy-presentation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: presentations/aggregates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: yes | slidev build --base /event-storming-to-code/
      - name: Debug
        run: pwd && ls dist -al
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}